-- =====================================================
-- Smart Grocery Inventory Management System
-- Database Creation Script for Apache Derby
-- =====================================================

CREATE TABLE CATEGORY (
    CATEGORY_ID     INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    CATEGORY_NAME   VARCHAR(100) NOT NULL,
    AISLE_NUMBER    INTEGER NOT NULL,
    STORAGE_TYPE    VARCHAR(50) NOT NULL,
    SHELF_LIFE      VARCHAR(50) NOT NULL,
    DESCRIPTION     VARCHAR(500) NOT NULL,
    IS_PERISHABLE   VARCHAR(5) DEFAULT 'Yes',
    MIN_STOCK_LEVEL INTEGER DEFAULT 10,
    CONSTRAINT PK_CATEGORY PRIMARY KEY (CATEGORY_ID)
);

CREATE TABLE SUPPLIER (
    SUPPLIER_ID       INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    SUPPLIER_NAME     VARCHAR(150) NOT NULL,
    CONTACT_PERSON    VARCHAR(100) NOT NULL,
    EMAIL             VARCHAR(150) NOT NULL,
    PHONE             VARCHAR(30) NOT NULL,
    ADDRESS           VARCHAR(300) NOT NULL,
    PRODUCTS_SUPPLIED VARCHAR(100) NOT NULL,
    DELIVERY_SCHEDULE VARCHAR(50),
    NOTES             VARCHAR(500),
    CONSTRAINT PK_SUPPLIER PRIMARY KEY (SUPPLIER_ID)
);

CREATE TABLE GROCERY_ITEM (
    ITEM_ID       INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    ITEM_NAME     VARCHAR(150) NOT NULL,
    BRAND         VARCHAR(100) NOT NULL,
    CATEGORY      VARCHAR(50) NOT NULL,
    QUANTITY      INTEGER NOT NULL,
    PRICE         DOUBLE NOT NULL,
    EXPIRY_DATE   DATE NOT NULL,
    SUPPLIER      VARCHAR(150),
    DESCRIPTION   VARCHAR(500),
    CONSTRAINT PK_GROCERY_ITEM PRIMARY KEY (ITEM_ID)
);
